app/Http/routes.php
<?php

Route::auth();
Route::get('/', 'HomeController@index');

//cookie tahun
// Route::resource('tahun', 'Web\Admin\TahunAjaranController');
Route::get('tahun', 'Web\Admin\TahunAjaranController@coota');
Route::resource('home', 'HomeController');
Route::resource('admin/beranda', 'Web\Admin\BerandaProController');

// jurusan
Route::resource('admin/jurusan', 'Web\Admin\JurusanController');
Route::resource('admin/kelas', 'Web\Admin\KelasController');

//siswa
Route::resource('admin/siswa', 'Web\Admin\SiswaController');
Route::resource('admin/siswa/hapus', 'Web\Admin\SiswaController@hapus');
Route::resource('admin/siswa/balikin', 'Web\Admin\SiswaController@balikin');
Route::resource('admin/siswa/destroy', 'Web\Admin\SiswaController@destroy');

//guru
Route::resource('admin/guru', 'Web\Admin\GuruController');
Route::resource('admin/guru/hapus', 'Web\Admin\GuruController@hapus');
Route::resource('admin/guru/balikin', 'Web\Admin\GuruController@balikin');
Route::resource('admin/guru/destroy', 'Web\Admin\GuruController@destroy');

//akun
Route::resource('admin/akun/admin', 'Web\Admin\AkunController');
Route::resource('admin/akun/guru', 'Web\Admin\AkunGuruController');
Route::resource('admin/akun/siswa', 'Web\Admin\AkunSiswaController');

//mata pelajaran
Route::resource('admin/mapel/na', 'Web\Admin\MataPelajaranController');
Route::resource('admin/mapel/pro', 'Web\Admin\MapelProController');

//kotak sampah
Route::resource('admin/sampah', 'Web\Admin\KotakSampahController');

//buku
Route::resource('admin/buku', 'Web\Admin\BukuController');
Route::get('admin/buku/tambahview/{id}', 'Web\Admin\BukuController@tambahview');

//soal
Route::resource('admin/soal', 'Web\Admin\SoalController');

//nilai
Route::resource('admin/nilai', 'Web\Admin\NilaiController');

/////////////////////////////////////////////////////////////////////////////
// GURU
////////////////////////////////////////////////////////////////////////////
// beranda
Route::resource('guru/beranda', 'Web\Guru\BerandaController');

// siswa
Route::resource('guru/siswa', 'Web\Guru\SiswaController');

// akun
Route::resource('guru/akun', 'Web\Guru\AkunController');

// buku
Route::resource('guru/buku', 'Web\Guru\BukuController');
Route::get('guru/buku/tambahview/{id}', 'Web\Guru\BukuController@tambahview');

// nilai
Route::resource('guru/nilai', 'Web\Guru\NilaiController');

// pengaturan
Route::resource('guru/pengaturan', 'Web\Guru\PengaturanController');

//soal
Route::resource('guru/soal', 'Web\Guru\SoalController');

/////////////////////////////////////////////////////////////////////////////
// SISWA
////////////////////////////////////////////////////////////////////////////
// beranda
Route::resource('siswa/beranda', 'Web\Siswa\BerandaController');

// akun
Route::resource('siswa/akun', 'Web\Siswa\AkunController');

// buku
Route::resource('siswa/buku', 'Web\Siswa\BukuController');
Route::get('siswa/buku/tambahview/{id}', 'Web\Siswa\BukuController@tambahview');

// nilai
Route::resource('siswa/nilai', 'Web\Siswa\NilaiController');

// ujian
Route::resource('siswa/ujian', 'Web\Siswa\UjianController');

// pengaturan
Route::resource('siswa/pengaturan', 'Web\Siswa\PengaturanController');

app/Http/Controllers/Web/Admin/SiswaController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Http\Requests\CreateSiswaRequest;
use App\Http\Requests\SiswaRequest;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;

use App\Siswa;
use App\User;
use App\Kelas;
use App\TahunAjaran;

use Alert;
use DB;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('akses:admin');
    }

    public function index(Request $request)
    {
        $q = $request->get('q');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 15 - 14;
        }else{
            $no=1;
        }

        $kelas = Kelas::lists('kode_kelas', 'id');

        $siswa = Siswa::where('nama', 'LIKE', '%'.$q.'%')
            ->where('hapus', '0')
            ->orderBy('nama','asc')
            ->paginate(15);

        return view('admin.siswa.siswa', compact('siswa', 'no' ,'q'));
    }

    public function create(Request $request)
    {
        return view('admin.siswa.tambah_siswa');
    }

    public function store(CreateSiswaRequest $request)
    {
        // SIMPAN DATA SISWA
        $dataSiswa = $request->only('jk','no_induk','nama','telp','hapus');
        
        if ($request->hasFile('photo')) {
            $dataSiswa['photo'] = $this->savePhoto($request->file('photo'));
        } else {
            if($request->jk == 'L'){
              $dataSiswa['photo'] = 'avatar1.png';
            } else {
              $dataSiswa['photo'] = 'avatar3.png';
            }
        }

        Siswa::create($dataSiswa);

        // SIMPAN DATA USER
        User::create([
            'no_induk'  => $request->no_induk,
            'email'     => $request->email,
            'password'  => bcrypt('smkpelita'),
            'api_token' => bcrypt($request->no_induk),
            'akses'      => 'siswa'
        ]);

        $notification = array(
            'message' => 'Siswa dengan nama '.$request->get('nama').' telah ditambahkan.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.siswa.index')->with($notification);
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
  
        $siswa      = Siswa::findOrFail($id); 
  
        return view('admin.siswa.edit_siswa', compact('siswa'));
    }

    public function update(SiswaRequest $request, $id)
    {
        // SIMPAN DATA SISWA
        $siswa = Siswa::findOrFail($id);
        $user = User::where('no_induk',$siswa->no_induk);

        $dataSiswa = $request->only('no_induk','nama','jk','telp','hapus');

        if ($request->hasFile('photo')) {
            $dataSiswa['photo'] = $this->savePhoto($request->file('photo'));
            if (($siswa->photo == 'avatar1.png')||($siswa->photo == 'avatar3.png')) {

            } else {
              $this->deletePhoto($siswa->photo);
            }
        } else {
            if($siswa->photo !== ('avatar1.png')||('avatar3.png')) {
              $dataSiswa['photo'] = $siswa->photo;
            } elseif ($request->jk == 'L') {
              $dataSiswa['photo'] = 'avatar1.png';
            } else {
              $dataSiswa['photo'] = 'avatar3.png';
            }
        }

        $siswa->update($dataSiswa);

        $dataUser = $request->only('no_induk','email');
        $user->update($dataUser);
        
        $notification = array(
            'message' => 'Data Siswa dengan nama '.$request->get('nama').' telah diubah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.siswa.index')->with($notification);
    }

    // HAPUS DATA SISWA SEMENTARA
    public function hapus($id)
    {
        $hapus = Siswa::findOrFail($id);
  
        DB::update('update siswas set hapus = "1" where id = '.$id);

        $notification = array(
            'message' => 'Data Siswa dengan nama '.$hapus->nama.' telah dihapus.',
            'alert-type' => 'warning'
        );

        return redirect()->route('admin.siswa.index')->with($notification);
    }

    // KEMBALIKAN DATA SISWA SEMENTARA
    public function balikin($id)
    {
        $hapus = Siswa::findOrFail($id);

        DB::update('update siswas set hapus = "0" where id = '.$id);
        $notification = array(
            'message' => 'Data Siswa dengan nama '.$hapus->nama.' telah dikembalikan.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.sampah.index')->with($notification);
    }

    public function destroy($id)
    {
        $hapus = Siswa::findOrFail($id);

        $notification = array(
            'message' => 'Data Siswa dengan nama '.$hapus->nama.' telah dihapus permanen.',
            'alert-type' => 'error'
        );

        //delete siswa
        $siswa      = Siswa::find($id);
  
        if ($siswa->photo !== ('avatar1.png')&&('avatar3.png')) $this->deletePhoto($siswa->photo);
  
        //delete siswa
        $siswa->delete();
  
        //delete user
        $user = User::where('no_induk',$siswa->no_induk);
        $user->delete();
  
        return redirect()->route('admin.siswa.index')->with($notification);
    }

    protected function savePhoto(UploadedFile $photo)
    {
      $fileName = str_random(40) . '.' . $photo->guessClientExtension();
      $destinationPath = 'itlabil/images/siswa';
      $photo->move($destinationPath, $fileName);
      return $fileName;
    }

    public function deletePhoto($filename)
    {
      $path = 'itlabil/images/siswa/'.$filename;
      return File::delete($path);
    }
}

app/Http/Controllers/Web/Guru/SiswaController.php
<?php

namespace App\Http\Controllers\Web\Guru;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Siswa;
use App\User;
use App\Kelas;
use App\TahunAjaran;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('akses:guru');
    }

    public function index(Request $request)
    {
        $tahun_ajaran = $request->cookie('tahun_ajaran');

        $q = $request->get('q');
        $kelas_id = $request->get('kelas_id');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 15 - 14;
        }else{
            $no=1;
        }

        $kelas = Kelas::lists('kode_kelas', 'id');

        $siswa = Siswa::where('nama', 'LIKE', '%'.$q.'%')
            ->where('kelas_id', 'LIKE', '%'.$kelas_id.'%')
            ->where('tahun_ajaran', $tahun_ajaran)
            ->where('hapus', '0')
            ->orderBy('kelas_id','asc')
            ->orderBy('nama','asc')
            ->paginate(15);

        return view('guru.siswa.siswa', compact('siswa', 'no' ,'q', 'kelas'));
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Web/Siswa/AkunController.php
<?php

namespace App\Http\Controllers\Web\Siswa;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\User;
use App\Siswa;

class AkunController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('akses:siswa');
    }

    public function index(Request $request)
    {

        $q = $request->get('q');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 10 - 9;
        }else{
            $no=1;
        }
        
        $nama = $request->cookie('nama');
        $siswa = Siswa::where('nama',$nama)->get()->first();

        return view('siswa.akun.akun', compact('siswa', 'no'));
    }
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Web/Siswa/BerandaController.php
<?php

namespace App\Http\Controllers\Web\Siswa;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Buku;
use App\Siswa;
class BerandaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('akses:siswa');
    }

    public function index(Request $request)
    {
        $q = $request->get('q');
        $r = $request->get('r');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 15 - 14;
        }else{
            $no=1;
        }

        $buku = Buku::where('judul_buku', 'LIKE', '%'.$q.'%')
            ->where('tingkat_kelas', 'LIKE', '%'.$r.'%')
            ->orderBy('id','desc')
            ->paginate(9);

        $populer = Buku::orderBy('tampil','desc')
            ->paginate(5);
        
        $kelas10 = Buku::where('tingkat_kelas','10')->count();
        $kelas11 = Buku::where('tingkat_kelas','11')->count();
        $kelas12 = Buku::where('tingkat_kelas','12')->count();
            
        return view('siswa.beranda.beranda', compact('buku','populer','kelas10','kelas11','kelas12', 'no' ,'q'));
    }
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Web/Siswa/BukuController.php
<?php

namespace App\Http\Controllers\Web\Siswa;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Buku;
use App\MateriBuku;
use App\Nilai;
use App\Soal;
use App\siswa;
use App\MataPelajaran;

class BukuController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('akses:siswa');
    }

    public function index(Request $request)
    {

        $q = $request->get('q');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 15 - 14;
        }else{
            $no=1;
        }

        $buku = Buku::where('judul_buku', 'LIKE', '%'.$q.'%')
            ->orderBy('id','desc')
            ->paginate(12);

        return view('siswa.buku.buku', compact('buku', 'no' ,'q'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(Request $request,$id)
    {
        $page = $request->get('page');
        if ($page=='') {
            $hal=0;
        }else{
            $hal= $page;
        }
        $buku = Buku::findOrFail($id);
        $jml  = MateriBuku::where('buku_id', $id)->count();
        $materi = MateriBuku::where('buku_id', $id)
                ->orderBy('materi','ASC')
                ->paginate(1);

        return view('siswa.buku.show_materi', compact('materi','buku','jml','hal'));
    }

    public function tambahview($id)
    {
        $buku = Buku::findOrFail($id);
        $dataBuku['tampil'] = $buku->tampil+1;
        $buku->update($dataBuku);
        
        return redirect('siswa/buku/'.$id);
    }

    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/siswa/edit_siswa.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Siswa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
                <a href="{{ url('/admin/siswa') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Data Siswa</a>
                <br><br>
            </div>
            <div class="col-md-12">
                {!! Form::model($siswa, ['route' => ['admin.siswa.update', $siswa],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                    @include('form._admin_edit_siswa', ['model' => $siswa])
                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/admin/siswa/siswa.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Siswa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data Siswa</h3>
                    </div>
                    <div class="box-body">
                      <div class="col-md-4">
                        {!! Form::open(['url' => 'admin/siswa', 'method'=>'get', 'class'=>'form-inline'])!!}
                          <div class="form-group {!! $errors->has('q') ? 'has-error' : '' !!}">
                              {!! Form::text('q', isset($q) ? $q : null, ['class'=>'form-control', 'placeholder' => 'Nama Siswa ....']) !!}
                              {!! $errors->first('q', '<p class="help-block">:message</p>') !!}
                          </div>
                          {!! Form::submit('Cari', ['class'=>'btn btn-primary']) !!}
                        {!! Form::close() !!}
                      </div>
                      <div class="col-md-4">
                            {!! Form::open(['url' => 'admin/siswa', 'method'=>'get', 'class'=>'form-inline'])!!}
                                <input type="hidden" name="q" value="">
                                {!! Form::submit('Semua Data Siswa', ['class'=>'btn btn-primary']) !!}
                            {!! Form::close() !!}
                          </div>
                      <div class="col-md-4" align="right">
                        <a href="{{ route('admin.siswa.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Siswa</a>
                        
                        {{-- <button class="btn btn-primary" data-toggle="modal" data-target="#upload"><i class="fa fa-upload"></i> Upload</button>

                        <div class="modal fade" id="upload" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" align="left">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <center><h4 class="modal-title" id="upload">
                                            Upload Data Siswa
                                        </h4></center>
                                    </div>

                                    <div class="modal-body">
                                      {!! Form::open(['url' => 'admin/siswa/upload', 'method'=>'post','enctype'=>'multipart/form-data', 'class'=>'form-horizontal','files'=>true])!!}
                                        <div class="form-group{{ $errors->has('upload_siswa') ? ' has-error' : '' }}">
                                            {!! Form::label('upload_siswa', 'Pilih File', ['class'=>'control-label col-sm-4']) !!}
                                            <div class="col-sm-8">
                                                {!! Form::file('upload_siswa') !!}
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            </div>
                                            <div class="col-sm-8">
                                                <small class="text-danger">{{ $errors->first('upload_siswa') }}</small>
                                                *Pastikan extensi file .csv
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        {{ Form::button('<i class="fa fa-upload"></i> Upload', ['value'=>'import','type'=>'submit','class' => 'btn btn-primary']) }}
                                    </div>
                                    {!! Form::close() !!}
                                </div>
                            </div>
                        </div> --}}

                      </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            @forelse ($siswa as $item)
                @if ($item->jk=='L')
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-red"><img src="../itlabil/images/siswa/{{$item->photo}}" class="img-circle" width="70px" alt="User Image"></span>

                            <div class="info-box-content">
                                <span class="info-box-text"><b>{{$item->nama}}</b></span>
                                <span class="info-box-text"><i class="fa fa-fw fa-black-tie"></i>{{$item->no_induk}}
                                <span class="info-box-text"><i class="fa fa-fw fa-phone"></i>{{$item->telp}}</span>
                                <span class="info-box-custom"><i class="fa fa-fw fa-phone"></i>{{$item->user->email}}</span>
                                <div align="right">
                                    <a href="{{ route('admin.siswa.edit', $item->id) }}"><i class="fa fa-fw fa-edit"></i></a>
                                    <a href="{{ url('admin/siswa/hapus', $item->id) }}"><i class="fa fa-fw fa-trash"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                @else
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-aqua"><img src="../itlabil/images/siswa/{{$item->photo}}" class="img-circle" width="70px" alt="User Image"></span>

                            <div class="info-box-content">
                                <span class="info-box-text"><b>{{$item->nama}}</b></span>
                                <span class="info-box-text"><i class="fa fa-fw fa-black-tie"></i>{{$item->no_induk}}
                                <span class="info-box-text"><i class="fa fa-fw fa-phone"></i>{{$item->telp}}</span>
                                <span class="info-box-custom"><i class="fa fa-fw fa-phone"></i>{{$item->user->email}}</span>
                                <div align="right">
                                    <a href="{{ route('admin.siswa.edit', $item->id) }}"><i class="fa fa-fw fa-edit"></i></a>
                                    <a href="{{ url('admin/siswa/hapus', $item->id) }}"><i class="fa fa-fw fa-trash"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                @endif
              @empty
              <div class="col-md-12 text-center">
                @if (isset($q))
                  <h1>:(</h1>
                  <p>Siswa tidak ditemukan.</p>
                @endif
                  <p><a href="{{ url('/admin/siswa') }}">Lihat semua data siswa <i class="fa fa-arrow-right"></i></a></p>
              </div>
            @endforelse
        </div>
        {{ $siswa->appends(compact('q', 'page'))->links() }}
    </section>
@endsection

resources/views/admin/siswa/tambah_siswa.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Siswa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
                <a href="{{ url('/admin/siswa') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Data Siswa</a>
                <br><br>
            </div>

            <div class="col-md-12">
                {!! Form::open(['route' => 'admin.siswa.store', 'class'=>'form-horizontal','files'=>true])!!}
                    @include('form._admin_siswa')
                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection