app/Http/routes.php
<?php

Route::auth();
Route::get('/', 'HomeController@index');

//cookie tahun
// Route::resource('tahun', 'Web\Admin\TahunAjaranController');
Route::get('tahun', 'Web\Admin\TahunAjaranController@coota');
Route::resource('home', 'HomeController');
Route::resource('admin/beranda', 'Web\Admin\BerandaProController');

// jurusan
Route::resource('admin/jurusan', 'Web\Admin\JurusanController');
Route::resource('admin/kelas', 'Web\Admin\KelasController');

//siswa
Route::resource('admin/siswa', 'Web\Admin\SiswaController');
Route::resource('admin/siswa/hapus', 'Web\Admin\SiswaController@hapus');
Route::resource('admin/siswa/balikin', 'Web\Admin\SiswaController@balikin');
Route::resource('admin/siswa/destroy', 'Web\Admin\SiswaController@destroy');

//guru
Route::resource('admin/guru', 'Web\Admin\GuruController');
Route::resource('admin/guru/hapus', 'Web\Admin\GuruController@hapus');
Route::resource('admin/guru/balikin', 'Web\Admin\GuruController@balikin');
Route::resource('admin/guru/destroy', 'Web\Admin\GuruController@destroy');

//akun
Route::resource('admin/akun/admin', 'Web\Admin\AkunController');
Route::resource('admin/akun/guru', 'Web\Admin\AkunGuruController');
Route::resource('admin/akun/siswa', 'Web\Admin\AkunSiswaController');

//mata pelajaran
Route::resource('admin/mapel/na', 'Web\Admin\MataPelajaranController');
Route::resource('admin/mapel/pro', 'Web\Admin\MapelProController');

//kotak sampah
Route::resource('admin/sampah', 'Web\Admin\KotakSampahController');

//buku
Route::resource('admin/buku', 'Web\Admin\BukuController');
Route::get('admin/buku/tambahview/{id}', 'Web\Admin\BukuController@tambahview');

//soal
Route::resource('admin/soal', 'Web\Admin\SoalController');

//nilai
Route::resource('admin/nilai', 'Web\Admin\NilaiController');

/////////////////////////////////////////////////////////////////////////////
// GURU
////////////////////////////////////////////////////////////////////////////
// beranda
Route::resource('guru/beranda', 'Web\Guru\BerandaController');

// siswa
Route::resource('guru/siswa', 'Web\Guru\SiswaController');

// akun
Route::resource('guru/akun', 'Web\Guru\AkunController');

// buku
Route::resource('guru/buku', 'Web\Guru\BukuController');
Route::get('guru/buku/tambahview/{id}', 'Web\Guru\BukuController@tambahview');

// nilai
Route::resource('guru/nilai', 'Web\Guru\NilaiController');

// pengaturan
Route::resource('guru/pengaturan', 'Web\Guru\PengaturanController');

//soal
Route::resource('guru/soal', 'Web\Guru\SoalController');

/////////////////////////////////////////////////////////////////////////////
// SISWA
////////////////////////////////////////////////////////////////////////////
// beranda
Route::resource('siswa/beranda', 'Web\Siswa\BerandaController');

// akun
Route::resource('siswa/akun', 'Web\Siswa\AkunController');

// buku
Route::resource('siswa/buku', 'Web\Siswa\BukuController');
Route::get('siswa/buku/tambahview/{id}', 'Web\Siswa\BukuController@tambahview');

// nilai
Route::resource('siswa/nilai', 'Web\Siswa\NilaiController');

// ujian
Route::resource('siswa/ujian', 'Web\Siswa\UjianController');

// pengaturan
Route::resource('siswa/pengaturan', 'Web\Siswa\PengaturanController');

app/Buku.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    protected $table = 'bukus';

    protected $fillable = [
        'guru_id','mata_pelajaran_id','tingkat_kelas','judul_buku','photo','tampil',
    ];

    // relasi ke guru
    public function guru()
    {
        return $this->belongsTo('App\Guru', 'guru_id');
    }

    // relasi ke mapel
    public function mapel()
    {
        return $this->belongsTo('App\MataPelajaran', 'mata_pelajaran_id');
    }

    // relasi one to many ke soal
    public function soal()
    {
        return $this->hasMany('App\Soal');
    }
    
    // relasi one to many ke materi
    public function materi()
    {
        return $this->hasMany('App\MateriBuku');
    }

    // relasi one to many ke nilai
    public function nilai()
    {
        return $this->hasMany('App\Nilai');
    }

    //relasi one to one ke populer
    public function populer()
    {
        return $this->hasOne('App\Populer');
    }
}

app/Http/Controllers/Web/Admin/BukuController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\BukuRequest;
use App\Http\Controllers\Controller;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;

use App\Buku;
use App\Nilai;
use App\Soal;
use App\Guru;
use App\MataPelajaran;
use App\Populer;

use DB;

class BukuController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('akses:admin');
    }

    public function index(Request $request)
    {

        $q = $request->get('q');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 15 - 14;
        }else{
            $no=1;
        }

        $buku = Buku::where('judul_buku', 'LIKE', '%'.$q.'%')
            ->orderBy('id','desc')
            ->paginate(12);

        return view('admin.buku.buku', compact('buku', 'no' ,'q'));
    }

    public function create()
    {
        $guru = Guru::lists('nama', 'id');
        $mapel = MataPelajaran::orderBy('jurusan_id','asc')
                        ->orderBy('mata_pelajaran','asc')
                        ->lists('mata_pelajaran', 'id');

        return view('admin.buku.tambah_buku',compact('guru','mapel'));
    }

    public function store(BukuRequest $request)
    {
        $dataBuku = $request->only('guru_id','mata_pelajaran_id','tingkat_kelas','judul_buku');
        // $dataBuku['buku'] = $this->savePdf($request->file('buku'));

        $mapel = MataPelajaran::where('id',$request->mata_pelajaran_id)->get()->first();

        if ($request->hasFile('photo')) {
            $dataBuku['photo'] = $this->savePhoto($request->file('photo'));
        } else {
            if ($mapel->jurusan_id=='2') {
                $dataBuku['photo'] = 'cover_ap.jpg';
            } else if ($mapel->jurusan_id=='3') {
                $dataBuku['photo'] = 'cover_ak.jpg';
            } else if ($mapel->jurusan_id=='4') {
                $dataBuku['photo'] = 'cover_pms.jpg';
            } else if ($mapel->jurusan_id=='5') {
                $dataBuku['photo'] = 'cover_tkj.jpg';
            } else if ($mapel->jurusan_id=='6') {
                $dataBuku['photo'] = 'cover_mm.jpg';
            } else if ($mapel->jurusan_id=='7') {
                $dataBuku['photo'] = 'cover_fm.jpg';
            } else {
                $dataBuku['photo'] = 'cover_na.jpg';
            }
        }
        $dataBuku['tampil'] = 0;

        Buku::create($dataBuku);

        $notification = array(
            'message' => 'Buku '.$request->get('judul_buku').' telah ditambahkan.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.buku.index')->with($notification);
    }

    public function show($id)
    {
        $buku = Buku::findOrFail($id);
        $path = 'itlabil/images/buku/'.$buku->buku;
        return response()->file($path);
    }

    public function tambahview($id)
    {
        $buku = Buku::findOrFail($id);
        $dataBuku['tampil'] = $buku->tampil+1;
        $buku->update($dataBuku);
        
        return redirect('admin/buku/'.$id);
    }

    public function edit($id)
    {
        $guru = Guru::lists('nama', 'id');
        $buku = Buku::findOrFail($id);

        $mapel = MataPelajaran::orderBy('jurusan_id','asc')
                        ->orderBy('mata_pelajaran','asc')
                        ->lists('mata_pelajaran', 'id');

        return view('admin.buku.edit_buku', compact('buku','guru','mapel'));
    }

    public function update(Request $request, $id)
    {
        $buku = Buku::findOrFail($id);

        $dataBuku = $request->only('guru_id','mata_pelajaran_id','tingkat_kelas','judul_buku');

        if ($request->hasFile('photo')) {
            if ($buku->photo=="cover_ap.jpg"||$buku->photo=="cover_ak.jpg"||$buku->photo=="cover_pms.jpg"||$buku->photo=="cover_tkj.jpg"||$buku->photo=="cover_mm.jpg"||$buku->photo=="cover_fm.jpg"||$buku->photo=="cover_na.jpg") {
                $dataBuku['photo'] = $this->savePhoto($request->file('photo'));
            } else {
                $this->deletePhoto($buku->photo);
                $dataBuku['photo'] = $this->savePhoto($request->file('photo'));
            }
        }

        // if ($request->hasFile('buku')) {
        //     $this->deletePhoto($buku->buku);
        //     $dataBuku['buku'] = $this->savePdf($request->file('buku'));
        // }
        
        $buku->update($dataBuku);
        $notification = array(
            'message' => 'Buku '.$request->get('judul_buku').' telah diubah.',
            'alert-type' => 'info'
        );
        return redirect()->route('admin.buku.index')->with($notification);
    }

    public function destroy($id)
    {
        $hapus = Buku::findOrFail($id);
        $notification = array(
            'message' => 'Buku dengan judul '.$hapus->judul_buku.' telah dihapus.',
            'alert-type' => 'error'
        );

        $buku = Buku::findOrFail($id);

        if ($buku->photo !== ($buku->photo=="cover_ap.jpg"||$buku->photo=="cover_ak.jpg"||$buku->photo=="cover_pms.jpg"||$buku->photo=="cover_tkj.jpg"||$buku->photo=="cover_mm.jpg"||$buku->photo=="cover_fm.jpg"||$buku->photo=="cover_na.jpg")) $this->deletePhoto($buku->photo);
        
        // $this->deletePdf($buku->buku);

        //delete soal
        $soal = Soal::where('buku_id',$buku->id);
        $soal->delete();

        //delete nilai
        $nilai = Nilai::where('buku_id',$buku->id);
        $nilai->delete();

        //delete guru
        $buku->delete();

        return redirect()->route('admin.buku.index')->with($notification);
    }

    protected function savePhoto(UploadedFile $photo)
    {
      $fileName = str_random(40) . '.' . $photo->guessClientExtension();
      $destinationPath = 'itlabil/images/cover';
      $photo->move($destinationPath, $fileName);
      return $fileName;
    }

    public function deletePhoto($filename)
    {
      $path = 'itlabil/images/cover/'. $filename;
      return File::delete($path);
    }

    protected function savePdf(UploadedFile $pdf)
    {
      $fileName = str_random(40) . '.' . $pdf->guessClientExtension();
      $destinationPath = 'itlabil/images/buku';
      $pdf->move($destinationPath, $fileName);
      return $fileName;
    }

    public function deletePdf($filename)
    {
      $path = 'itlabil/images/buku/'. $filename;
      return File::delete($path);
    }
}

app/Http/Controllers/Web/Guru/BukuController.php
<?php

namespace App\Http\Controllers\Web\Guru;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;

use App\Buku;
use App\Nilai;
use App\Soal;
use App\Guru;
use App\MataPelajaran;

class BukuController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('akses:guru');
    }

    public function index(Request $request)
    {

        $q = $request->get('q');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 15 - 14;
        }else{
            $no=1;
        }

        $buku = Buku::where('judul_buku', 'LIKE', '%'.$q.'%')
            ->orderBy('id','desc')
            ->paginate(12);

        return view('guru.buku.buku', compact('buku', 'no' ,'q'));
    }

    public function create()
    {
        $guru = Guru::lists('nama', 'id');
        $mapel = MataPelajaran::orderBy('jurusan_id','asc')
                        ->orderBy('mata_pelajaran','asc')
                        ->lists('mata_pelajaran', 'id');

        return view('guru.buku.tambah_buku',compact('guru','mapel'));
    }

    public function store(BukuRequest $request)
    {
        $dataBuku = $request->only('guru_id','mata_pelajaran_id','tingkat_kelas','judul_buku');
        $dataBuku['buku'] = $this->savePdf($request->file('buku'));

        $mapel = MataPelajaran::where('id',$request->mata_pelajaran_id)->get()->first();

        if ($request->hasFile('photo')) {
            $dataBuku['photo'] = $this->savePhoto($request->file('photo'));
        } else {
            if ($mapel->jurusan_id=='2') {
                $dataBuku['photo'] = 'cover_ap.jpg';
            } else if ($mapel->jurusan_id=='3') {
                $dataBuku['photo'] = 'cover_ak.jpg';
            } else if ($mapel->jurusan_id=='4') {
                $dataBuku['photo'] = 'cover_pms.jpg';
            } else if ($mapel->jurusan_id=='5') {
                $dataBuku['photo'] = 'cover_tkj.jpg';
            } else if ($mapel->jurusan_id=='6') {
                $dataBuku['photo'] = 'cover_mm.jpg';
            } else if ($mapel->jurusan_id=='7') {
                $dataBuku['photo'] = 'cover_fm.jpg';
            } else {
                $dataBuku['photo'] = 'cover_na.jpg';
            }
        }
        $dataBuku['tampil'] = 0;

        Buku::create($dataBuku);

        $notification = array(
            'message' => 'Buku '.$request->get('judul_buku').' telah ditambahkan.',
            'alert-type' => 'success'
        );

        return redirect()->route('guru.buku.index')->with($notification);
    }

    public function show($id)
    {
        $buku = Buku::findOrFail($id);
        $path = 'itlabil/images/buku/'.$buku->buku;
        return response()->file($path);
    }

    public function tambahview($id)
    {
        $buku = Buku::findOrFail($id);
        $dataBuku['tampil'] = $buku->tampil+1;
        $buku->update($dataBuku);
        
        return redirect('guru/buku/'.$id);
    }

    public function edit($id)
    {
        $guru = Guru::lists('nama', 'id');
        $buku = Buku::findOrFail($id);

        $mapel = MataPelajaran::orderBy('jurusan_id','asc')
                        ->orderBy('mata_pelajaran','asc')
                        ->lists('mata_pelajaran', 'id');

        return view('guru.buku.edit_buku', compact('buku','guru','mapel'));
    }

    public function update(Request $request, $id)
    {
        $buku = Buku::findOrFail($id);

        $dataBuku = $request->only('guru_id','mata_pelajaran_id','tingkat_kelas','judul_buku');

        if ($request->hasFile('photo')) {
            if ($buku->photo=="cover_ap.jpg"||$buku->photo=="cover_ak.jpg"||$buku->photo=="cover_pms.jpg"||$buku->photo=="cover_tkj.jpg"||$buku->photo=="cover_mm.jpg"||$buku->photo=="cover_fm.jpg"||$buku->photo=="cover_na.jpg") {
                $dataBuku['photo'] = $this->savePhoto($request->file('photo'));
            } else {
                $this->deletePhoto($buku->photo);
                $dataBuku['photo'] = $this->savePhoto($request->file('photo'));
            }
        }

        if ($request->hasFile('buku')) {
            $this->deletePhoto($buku->buku);
            $dataBuku['buku'] = $this->savePdf($request->file('buku'));
        }
        
        $buku->update($dataBuku);
        $notification = array(
            'message' => 'Buku '.$request->get('judul_buku').' telah diubah.',
            'alert-type' => 'info'
        );
        return redirect()->route('guru.buku.index')->with($notification);
    }

    public function destroy($id)
    {
        $hapus = Buku::findOrFail($id);
        $notification = array(
            'message' => 'Buku dengan judul '.$hapus->judul_buku.' telah dihapus.',
            'alert-type' => 'error'
        );

        $buku = Buku::findOrFail($id);

        if ($buku->photo !== ($buku->photo=="cover_ap.jpg"||$buku->photo=="cover_ak.jpg"||$buku->photo=="cover_pms.jpg"||$buku->photo=="cover_tkj.jpg"||$buku->photo=="cover_mm.jpg"||$buku->photo=="cover_fm.jpg"||$buku->photo=="cover_na.jpg")) $this->deletePhoto($buku->photo);
        
        $this->deletePdf($buku->buku);

        //delete soal
        $soal = Soal::where('buku_id',$buku->id);
        $soal->delete();

        //delete nilai
        $nilai = Nilai::where('buku_id',$buku->id);
        $nilai->delete();

        //delete guru
        $buku->delete();

        return redirect()->route('guru.buku.index')->with($notification);
    }

    protected function savePhoto(UploadedFile $photo)
    {
      $fileName = str_random(40) . '.' . $photo->guessClientExtension();
      $destinationPath = 'itlabil/images/cover';
      $photo->move($destinationPath, $fileName);
      return $fileName;
    }

    public function deletePhoto($filename)
    {
      $path = 'itlabil/images/cover/'. $filename;
      return File::delete($path);
    }

    protected function savePdf(UploadedFile $pdf)
    {
      $fileName = str_random(40) . '.' . $pdf->guessClientExtension();
      $destinationPath = 'itlabil/images/buku';
      $pdf->move($destinationPath, $fileName);
      return $fileName;
    }

    public function deletePdf($filename)
    {
      $path = 'itlabil/images/buku/'. $filename;
      return File::delete($path);
    }
}

resources/views/admin/buku/buku.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Buku
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-body">
                      <div class="col-md-4">
                        {!! Form::open(['url' => 'admin/buku', 'method'=>'get', 'class'=>'form-inline'])!!}
                          <div class="form-group {!! $errors->has('q') ? 'has-error' : '' !!}">
                              {!! Form::text('q', isset($q) ? $q : null, ['class'=>'form-control', 'placeholder' => 'Nama Buku ....']) !!}
                              {!! $errors->first('q', '<p class="help-block">:message</p>') !!}
                          </div>
                          {!! Form::submit('Cari', ['class'=>'btn btn-primary']) !!}
                        {!! Form::close() !!}
                      </div>
                      <div class="col-md-4">
                            {!! Form::open(['url' => 'admin/buku', 'method'=>'get', 'class'=>'form-inline'])!!}
                                <input type="hidden" name="q" value="">
                                {!! Form::submit('Semua Buku', ['class'=>'btn btn-primary']) !!}
                            {!! Form::close() !!}
                          </div>
                      <div class="col-md-4" align="right">
                        <a href="{{ route('admin.buku.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Buku</a>
                      </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            @forelse ($buku as $item)
                <div class="col-md-3">
                    <div class="box">
                        <div class="box-body box-profile">
                            <img class="img-cover img-responsive" src="{{url('itlabil/images/cover')}}/{{ $item->photo }}" alt="User profile picture">
                            <h4 class="text-judul text-center" title="{{$item->judul_buku}}">{{$item->judul_buku}}</h3>
                            <p class="text-center"><i class="fa fa-fw fa-user"></i>{{$item->guru->nama}}</p>
                            <p class="text-center">
                                <small class="label bg-red"><i class="fa fa-fw fa-black-tie"></i> {{$item->tingkat_kelas}}</small>
                                <small class="label bg-blue"><i class="fa fa-fw fa-book"></i> {{$item->mapel->mata_pelajaran}}</small>
                                <small class="label bg-yellow"><i class="fa fa-fw fa-eye"></i> {{$item->tampil}}</small>
                            </p>
                            <p class="text-center">
                                <div class="col-md-6" align="right">
                                    <a href="{{url('admin/buku/tambahview',$item->id) }}" target="_blank" class="btn btn-primary"><b>Baca</b></a>
                                </div>
                                <div class="col-md-6" align="left">
                                    <a href="{{route('admin.buku.edit',$item->id) }}" class="btn btn-success"><b>Ubah</b></a>
                                </div>
                            </p><br><br>
                            <p class="text-center">
                                <div class="col-md-6" align="right">
                                    <a href="{{route('admin.soal.index') }}" class="btn btn-info"><b>Soal</b></a>
                                </div>
                                <div class="col-md-6" align="left">
                                    {{ Form::open(['route' => ['admin.buku.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                        {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                    {{ Form::close() }}
                                </div>
                            </p>
                        </div>
                    </div>
                </div>
            @empty
                <div class="col-md-12 text-center">
                    @if (isset($q))
                        <h1>:(</h1>
                        <p>buku tidak ditemukan.</p>
                    @endif
                    <p><a href="{{ url('/admin/buku') }}">Lihat semua buku <i class="fa fa-arrow-right"></i></a></p>
                </div>
            @endforelse
        </div>
        {{ $buku->appends(compact('q', 'page'))->links() }}
    </section>
@endsection

resources/views/admin/buku/edit_buku.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Buku
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Buku</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($buku, ['route' => ['admin.buku.update', $buku],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_edit_buku', ['model' => $buku])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/buku/tambah_buku.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Buku
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
                <a href="{{ url('/admin/buku') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Data buku</a>
                <br><br>
            </div>

            <div class="col-md-12">
                {!! Form::open(['route' => 'admin.buku.store', 'class'=>'form-horizontal','files'=>true])!!}
                    @include('form._admin_buku')
                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection